name: CD for LogMeIn

on:
  push:
    branches:
      - main    # Déploiement seulement sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Cloner le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Builder et Pousser l'image backend
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: paoza33/logmein-backend:latest

      # 5️⃣ Builder et Pousser l'image frontend
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: paoza33/logmein-frontend:latest

      # 6️⃣ (Optionnel) Déployer sur un serveur distant via SSH
      # Décommenter et configurer si tu as un VPS ou serveur
      #- name: Deploy to VPS
      #  uses: appleboy/ssh-action@v0.1.10
      #  with:
      #    host: ${{ secrets.VPS_HOST }}
      #    username: ${{ secrets.VPS_USER }}
      #    key: ${{ secrets.VPS_SSH_KEY }}
      #    script: |
      #      docker pull paoza33/logmein-backend:latest
      #      docker pull paoza33/logmein-frontend:latest
      #      docker-compose up -d
